config/routes.rb
Rails.application.routes.draw do

  # FRONTEND IN STAGING SERVER
  # scope '/prestige' do
  #   get 'about', to: 'public#about', as: 'about'
  #   get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  #   get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  #   get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  #   get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  #   get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  #   get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  #   get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  #   get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  #   get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  #   get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  #   get '/', to: "public#home", as: 'root'
  # end

  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  },
  path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register'
  }

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'

    resources :users
    resources :admins
    resources :articles do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
        get :download
      end
    end
    resources :contacts do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :services do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end

  root 'public#home'
  get 'home', to: 'public#home', as: 'home'
  get 'about', to: 'public#about', as: 'about'
  get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  # get '/', to: "public#home", as: 'root'

end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController
  defaults resource_class: Admin, collection_name: 'admins', instance_name: 'admin'
  include UserFilter

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Admins", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < Backend::ResourcesController
  layout 'backend'
  before_filter :authenticate_admin!, :prepare_action
  protect_from_forgery with: :exception

  def authenticate_admin!
    unless current_user.present? && (current_user.is_admin?)
      redirect_to backend_dashboard_path, alert: "Can't Access this page"
    end
  end

  protected
    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end

    def prepare_action
      @messages = Contact.latest.limit(5)
    end
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < Backend::ApplicationController
  defaults resource_class: Article, collection_name: 'articles', instance_name: 'article'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Articles", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/blogs_controller.rb
class Backend::BlogsController < Backend::ApplicationController
  defaults resource_class: Blog, collection_name: 'blogs', instance_name: 'blog'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Blogs", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/contacts_controller.rb
class Backend::ContactsController < Backend::ApplicationController
  defaults resource_class: Contact, collection_name: 'contacts', instance_name: 'contact'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Contacts", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  def show
    add_breadcrumb "Show"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
  add_breadcrumb "Dashboard", :backend_dashboard_path

  def dashboard
  end
end

app/controllers/backend/landing_pages_controller.rb
class Backend::LandingPagesController < Backend::ApplicationController
  defaults resource_class: LandingPage, collection_name: 'landing_pages', instance_name: 'landing_page'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Landing Page", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::ApplicationController
  defaults resource_class: Product, collection_name: 'products', instance_name: 'product'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Products", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def download
    @product = Product.find params[:id]
    url = @product.video.url
    file_path = url.split("?").first
    if !file_path.nil?
      send_file "#{Rails.root}/public#{file_path}", :x_sendfile => true 
    else 
      redirect_to :back
    end
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/resources_controller.rb
class Backend::ResourcesController < InheritedResources::Base
  include Parameters

  def create
    create! do |success, failure|
      success.html { redirect_to collection_path }
      failure.html do
        flash[:error] = resource.errors.full_messages
        redirect_to :back
      end
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to collection_path }
    end
  end
end

app/controllers/backend/services_controller.rb
class Backend::ServicesController < Backend::ApplicationController
  defaults resource_class: Service, collection_name: 'services', instance_name: 'service'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Services", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ApplicationController
  defaults resource_class: User, collection_name: 'users', instance_name: 'user'
  include UserFilter

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Users", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::ApplicationController
  defaults resource_class: WebSetting, collection_name: 'web_settings', instance_name: 'web_setting'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Web Settings", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/views/backend/shareds/_breadcrumb.html.slim
.page-head
  h2.pull-left
    i.fa.fa-home
    = render_breadcrumbs :separator => ' / '
  .bread-crumb.pull-right
  .clearfix

app/views/backend/shareds/_footer.html.slim
footer class="footer"
  .container
    center
      | © 2015 Prestige Car Indonesia

app/views/backend/shareds/_heading.html.slim
.content-header
  h2 class="content-header-title"
    = table_name
  = render_breadcrumbs

app/views/backend/shareds/_nav.html.slim
.navbar
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
        | <i class="fa fa-cogs"></i>
      = link_to "#{image_tag 'logo.jpg'}".html_safe, backend_dashboard_path, class: 'navbar-brand navbar-brand-image'

    .navbar-collapse.collapse
      ul class="nav navbar-nav noticebar navbar-left"
        li class="dropdown"
          a href="page-notifications.html" class="dropdown-toggle" data-toggle="dropdown"
            | <i class="fa fa-envelope"></i>
            | <span class="navbar-visible-collapsed">&nbsp;Messages&nbsp;</span>

          ul class="dropdown-menu noticebar-menu" role="menu"   
            - @messages.each do |m|          
              li
                = link_to backend_contact_path(m), class: "noticebar-item" do
                  span class="noticebar-item-image"
                    = image_tag "no-image.png", style: "width: 50px"

                  span class="noticebar-item-body"
                    strong class="noticebar-item-title" From: #{m.full_name}
                    span class="noticebar-item-text"
                      = truncate(strip_tags(m.message), length: 20, omission: '...')
                    small class="noticebar-item-time" 
                      = m.try(:created_at).strftime("%B, %d, %Y")


            li class="noticebar-menu-view-all"
              = link_to 'View All Messages', backend_contacts_path

      ul class="nav navbar-nav navbar-right" 
        li 
          = link_to edit_backend_admin_path(current_user) do
            = current_user.email
        li class="dropdown navbar-profile"
          a class="dropdown-toggle" data-toggle="dropdown" href="javascript:"
            = image_tag current_user.profile.avatar.url(:small), class: "navbar-profile-avatar"
            | <i class="fa fa-caret-down"></i>
          ul class="dropdown-menu" role="menu"
            li
              = link_to edit_backend_admin_path(current_user)
                i class="fa fa-cogs"
                | &nbsp;&nbsp;Settings
            li class="divider"
            li
              = link_to destroy_user_session_path, method: 'delete' do 
                i class="fa fa-sign-out"
                | &nbsp;&nbsp;Logout

app/views/backend/shareds/_prepare_action.html.slim
= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_resource_path(resource), class: 'btn btn-xs btn-warning'
| &nbsp;
= link_to '<i class="fa fa-times"></i>'.html_safe, resource_path(resource), method: 'delete', class: 'btn btn-xs btn-danger', data: {confirm: confirmation}
| &nbsp;

- if params[:controller] == 'backend/contacts'
  = link_to '<i class="fa fa-search"></i>'.html_safe, resource_path(resource), class: 'btn btn-xs btn-info'

app/views/backend/shareds/_prepare_form.html.slim
.col-md-12
  .content-header
    h2 class="content-header-title"
      = "#{action_name} #{form_name}"
    = render_breadcrumbs

  = form_for [:backend, resource], method: form_method, html: {class: 'form'} do |f|
    = render partial: 'form', locals: {f: f}
    .break
    .row
      button class="btn btn-info pull-right" type="submit" SAVE
    .break

app/views/backend/shareds/_prepare_table.html.slim
.portlet-header
  .widget-head
    .pull-left
      / - unless params[:controller] == 'backend/contacts'
      = link_to '<i class="fa fa-reorder"></i> List'.html_safe, collection_path, class: 'btn btn-info btn-sm'
      | &nbsp;
      = link_to '<i class="fa fa-plus"></i> Create New'.html_safe, new_resource_path, class: 'btn btn-success btn-sm'

    .widget-icons.pull-right
      - if params[:controller] == 'backend/products' || params[:controller] == 'backend/blogs' || params[:controller] == 'backend/articles'
        button class="btn btn-info btn-sm" type="submit" name="commit" value="activated"
          | <i class="fa fa-check"></i> Activated
        | &nbsp;
        button class="btn btn-warning btn-sm" type="submit" name="commit" value="non_activated"
          | <i class="fa fa-exclamation"></i> Non Activated
        | &nbsp;

      - if params[:controller] == 'backend/contacts'
        button class="btn btn-info btn-sm" type="submit" name="commit" value="activated"
          | <i class="fa fa-check"></i> Already Check
        | &nbsp;
        button class="btn btn-warning btn-sm" type="submit" name="commit" value="non_activated"
          | <i class="fa fa-exclamation"></i> UnChecked
        | &nbsp;
      
      - unless params[:controller] == 'backend/web_settings'
        button class="btn btn-danger btn-sm" type="submit" name="commit" value="destroy_all"
          | <i class="fa fa-times"></i> Destroy All
        | &nbsp;
  br

app/views/backend/shareds/_search_form.html.slim
.row
  = form_for :search, url: collection_path, method: 'get' do
    .col-md-7
      h6 Find Results <b> #{collection.size} </b>
    .col-md-4
      = text_field_tag :key, nil, value: params[:key], class: 'form-control', placeholder: 'keywords..'
    .col-md-1.padding0
      button class="btn btn-info" type="submit" Search

app/views/backend/shareds/_search_form_product.html.slim
.row
  = form_for :search, url: collection_path, method: 'get' do 
    .col-md-12
      h6 Find Results <b> #{collection.size} </b>
    .col-md-5
      = text_field_tag :key, nil, value: params[:key], class: 'form-control', placeholder: 'keywords..' 
    .col-md-3
      = select_tag :category, options_for_select(Category.latest.pluck(:name), params[:category]), prompt: 'Choice Category', class: 'select2 form-control'
    .col-md-1.padding0
      button class="btn btn-info" type="submit" Search

app/views/backend/shareds/_top_menu.html.slim
.mainbar
  .container
    button type="button" class="btn mainbar-toggle" data-toggle="collapse" data-target=".mainbar-collapse"
      i class="fa fa-bars"
    .mainbar-collapse.collapse
      ul class="nav navbar-nav mainbar-nav"
        li class="#{active_sidebar?(:home, :dashboard)}"
          = link_to '<i class="fa fa-dashboard"></i>Dashboard'.html_safe, backend_dashboard_path
        li class="dropdown #{active_sidebar?(:articles, :all)}"
          a href="index.html#about" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
            | <i class="fa fa-newspaper-o"></i> News & Events <span class="caret"></span>
          ul.dropdown-menu
            li
              = link_to '<i class="fa fa-plus-square-o"></i> Create New'.html_safe, new_backend_article_path
            li class="divider"
            li
              = link_to '<i class="fa fa-align-justify"></i> List'.html_safe, backend_articles_path
        li class="dropdown #{active_sidebar?(:blogs, :all)}"
          a href="index.html#about" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
            | <i class="fa fa-film"></i> Video Blogs <span class="caret"></span>
          ul.dropdown-menu
            li
              = link_to '<i class="fa fa-plus-square-o"></i> Create New'.html_safe, new_backend_blog_path
            li class="divider"
            li
              = link_to '<i class="fa fa-align-justify"></i> List'.html_safe, backend_blogs_path
        li class="dropdown #{active_sidebar?(:products, :all)}"
          a href="index.html#about" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
            | <i class="fa fa-car"></i> Products <span class="caret"></span>
          ul.dropdown-menu
            li
              = link_to '<i class="fa fa-plus-square-o"></i> Create New'.html_safe, new_backend_product_path
            li class="divider"
            li
              = link_to '<i class="fa fa-align-justify"></i> List'.html_safe, backend_products_path
        li class="dropdown #{active_sidebar?(:landing_pages, :all)}"
          a href="index.html#about" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
            | <i class="fa fa-file-o"></i> Landing Pages <span class="caret"></span>
          ul.dropdown-menu
            li
              = link_to '<i class="fa fa-plus-square-o"></i> Create New'.html_safe, new_backend_landing_page_path
            li class="divider"
            li
              = link_to '<i class="fa fa-align-justify"></i> List'.html_safe, backend_landing_pages_path
        li class="#{active_sidebar?(:services, :all)}"
          = link_to '<i class="fa fa-star"></i>Services'.html_safe, backend_services_path
        li class="#{active_sidebar?(:contacts, :all)}"
          = link_to '<i class="fa fa-comments-o"></i> Contacts'.html_safe, backend_contacts_path
        li class="#{active_sidebar?(:admins, :all)}"
          = link_to '<i class="fa fa-user-secret"></i> Admins'.html_safe, backend_admins_path
        li class="#{active_sidebar?(:web_settings, :all)}"
          = link_to '<i class="fa fa-wrench"></i> Web Settings'.html_safe, backend_web_settings_path
        