config/routes.rb
Rails.application.routes.draw do

  # FRONTEND IN STAGING SERVER
  # scope '/prestige' do
  #   get 'about', to: 'public#about', as: 'about'
  #   get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  #   get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  #   get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  #   get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  #   get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  #   get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  #   get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  #   get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  #   get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  #   get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  #   get '/', to: "public#home", as: 'root'
  # end

  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  },
  path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register'
  }

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'

    resources :users
    resources :admins
    resources :articles do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
        get :download
      end
    end
    resources :contacts do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :services do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end

  root 'public#home'
  get 'home', to: 'public#home', as: 'home'
  get 'about', to: 'public#about', as: 'about'
  get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  # get '/', to: "public#home", as: 'root'

end

app/views/shareds/_footer.html.slim
footer.dealer-footer-wrapper
  .container
    .row
      .col-md-12
        .col-md-5.col-sm-12.col-xs-12
          h3 Prestige Image Motorcars
          .textwidget
            i.mk-theme-icon-office
            strong Jakarta Dealer
            em Jl. Pluit Karang Ayu, Blok. C1 Utara, No 11, Jakarta Utara
            br
            br
            i.mk-theme-icon-office
            strong Jakarta Office:
            em Jl. Pluit Permai No.5 Jakarta Utara (Opposite Pluit Vilage)

        .col-md-2.col-sm-12.col-xs-12
          h3 Capabities
          ul
            li
              = link_to 'Sporty Car Event', root_path
            li
              = link_to 'Design Elegant', root_path
            li
              = link_to 'Imaginatif', root_path

        .col-md-2.col-sm-12.col-xs-12
          h3 Need More
          ul
            li
              = link_to 'What we are?', root_path
            li
              = link_to 'Dealer Config', root_path
            li
              = link_to 'Sell Car', root_path

        .col-md-3.col-sm-12.col-xs-12
          form action="#" class="form-search-footer"
            .input-group
              input type="text" class="form-control" placeholder="Search for..."
              span class="input-group-btn"
                button class="btn btn-default" type="button"
                  i.fa.fa-search

          ul
            li
              = link_to 'Prestige Event', root_path
            li
              = link_to 'Otomotive Event', root_path

footer.sub-footer
  .container
    .col-md-12
      .item-holder
        span.mk-footer-corpyright
          | &copy; 2015&nbsp;
          = link_to 'Prestige Image Motorcars', root_path
          | . All Rights Reserved.

        ul.mk-footer-social
          li
            = link_to root_path
              i.fa.fa-facebook
          li
            = link_to root_path
              i.fa.fa-twitter
          li
            = link_to root_path
              i.fa.fa-google-plus
          li
            = link_to root_path
              i.fa.fa-instgaram

a.backtotop#upClick href="#"
  i.glyphicon.glyphicon-chevron-up

#search
  button type="button" class="close"
    | ×
  form
    input type="search" value="" placeholder="Input type keyword(s) to search"
    button type="submit" class="btn btn-prestige"
      i.fa.fa-search
      | &nbsp;Search

app/views/shareds/_navbar.html.slim
nav.navbar.navbar-default.menu-fixed-top.main-nav
  .container
    .col-md-12
      .row
        .navbar-header.page-scroll
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar

          = link_to root_path, class: 'navbar-brand'
            = image_tag 'logo.jpg', alt: 'YOUR TITLE'

        .collapse.navbar-collapse#dealer-nav
          #menu-scroll
            ul.nav.navbar-nav.navbar-right
              li
                = link_to root_path
                  | Home
              li
                = link_to product_v1_path
                  | Product
              li
                = link_to news_event_v2_path
                  | Event
              li
                = link_to video_blog_path
                  | Video Blog
              li
                = link_to about_path
                  | About Us
              li
                = link_to contact_us_path
                  | Contact Us
              li
                a href="#search"
                  i.fa.fa-search

app/views/shareds/_navbar_page.html.slim
nav.navbar.navbar-default.menu-fixed-top.main-nav.menu-page
  .container
    .col-md-12
      .row
        .navbar-header.page-scroll
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar

          = link_to root_path, class: 'navbar-brand'
            = image_tag 'logo.jpg', alt: 'YOUR TITLE'

        .collapse.navbar-collapse#dealer-nav
          #menu-scroll
            ul.nav.navbar-nav.navbar-right
              li
                = link_to root_path
                  | Home
              li
                = link_to product_v1_path
                  | Product
              li
                = link_to news_event_v2_path
                  | Event
              li
                = link_to video_blog_path
                  | Video Blog
              li
                = link_to about_path
                  | About Us
              li
                = link_to contact_us_path
                  | Contact Us
              li
                a href="#search"
                  i.fa.fa-search