config/routes.rb
Rails.application.routes.draw do

  # FRONTEND IN STAGING SERVER
  # scope '/prestige' do
  #   get 'about', to: 'public#about', as: 'about'
  #   get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  #   get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  #   get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  #   get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  #   get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  #   get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  #   get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  #   get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  #   get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  #   get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  #   get '/', to: "public#home", as: 'root'
  # end

  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  },
  path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register'
  }

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'

    resources :users
    resources :admins
    resources :articles do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
        get :download
      end
    end
    resources :contacts do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :services do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end

  root 'public#home'
  get 'home', to: 'public#home', as: 'home'
  get 'about', to: 'public#about', as: 'about'
  get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  # get '/', to: "public#home", as: 'root'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  before_create :prepare_code
  after_initialize :populate_galleries, :populate_overview

  include ScopeBased
  include TheSearch::ProductSearch
  
  scope :activated, ->{where(status: true)}

  belongs_to :user, foreign_key: 'user_id'

  has_many :specifications, as: :specificationable, dependent: :destroy
  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  has_many :galleries, as: :galleriable, dependent: :destroy
  accepts_nested_attributes_for :galleries, reject_if: :all_blank, allow_destroy: true

  has_attached_file :interior_image, styles: {
                      large:    '1200>',
                      small:    '300>'
                    },
                    default_url: 'no-image.png'

  validates_attachment :interior_image, content_type: {
    content_type: ["image/jpg", "image/jpeg", "image/png"]
  }

  has_attached_file :video

  def build_image(media_title, position=nil)
    gallery = self.galleries.build({title: media_title})
    gallery.position = position
  end

  def build_overview(media_title)
    specification = self.specifications.build({description: media_title})
  end

  def status?
    if self.status == true
      return '<label class="label label-success">Already Publish</label>'.html_safe
    else
      return '<label class="label label-danger">Pending</label>'.html_safe
    end
  end

  private
    def prepare_code
      self.code = SecureRandom.hex(3) if self.code.blank?
    end

    def populate_galleries
      if self.galleries.length < 4
        [
          'Cover',
          'Image1',
          'Image2',
          'Image3'
        ].each_with_index do |media_title, index|
          _galery = self.galleries.select{|g| g.title.to_s.downcase == media_title.downcase}.first
          unless _galery
            self.build_image(media_title, index+1)
          else
            _galery.position = index+1
          end
        end
      end if self.new_record?
    end

    def populate_overview
      if self.specifications.length < 4
        [
          'Overview 1',
          'Overview 2',
          'Overview 3',
          'Overview 4'
        ].each_with_index do |media_title, index|
          _overview = self.specifications.select{|g| g.description.to_s.downcase == media_title.downcase}.first
          unless _overview
            self.build_overview(media_title)
          end
        end
      end if self.new_record?
    end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController
  defaults resource_class: Admin, collection_name: 'admins', instance_name: 'admin'
  include UserFilter

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Admins", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < Backend::ResourcesController
  layout 'backend'
  before_filter :authenticate_admin!, :prepare_action
  protect_from_forgery with: :exception

  def authenticate_admin!
    unless current_user.present? && (current_user.is_admin?)
      redirect_to backend_dashboard_path, alert: "Can't Access this page"
    end
  end

  protected
    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end

    def prepare_action
      @messages = Contact.latest.limit(5)
    end
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < Backend::ApplicationController
  defaults resource_class: Article, collection_name: 'articles', instance_name: 'article'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Articles", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/blogs_controller.rb
class Backend::BlogsController < Backend::ApplicationController
  defaults resource_class: Blog, collection_name: 'blogs', instance_name: 'blog'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Blogs", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/contacts_controller.rb
class Backend::ContactsController < Backend::ApplicationController
  defaults resource_class: Contact, collection_name: 'contacts', instance_name: 'contact'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Contacts", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  def show
    add_breadcrumb "Show"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
  add_breadcrumb "Dashboard", :backend_dashboard_path

  def dashboard
  end
end

app/controllers/backend/landing_pages_controller.rb
class Backend::LandingPagesController < Backend::ApplicationController
  defaults resource_class: LandingPage, collection_name: 'landing_pages', instance_name: 'landing_page'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Landing Page", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::ApplicationController
  defaults resource_class: Product, collection_name: 'products', instance_name: 'product'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Products", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def download
    @product = Product.find params[:id]
    url = @product.video.url
    file_path = url.split("?").first
    if !file_path.nil?
      send_file "#{Rails.root}/public#{file_path}", :x_sendfile => true 
    else 
      redirect_to :back
    end
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/resources_controller.rb
class Backend::ResourcesController < InheritedResources::Base
  include Parameters

  def create
    create! do |success, failure|
      success.html { redirect_to collection_path }
      failure.html do
        flash[:error] = resource.errors.full_messages
        redirect_to :back
      end
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to collection_path }
    end
  end
end

app/controllers/backend/services_controller.rb
class Backend::ServicesController < Backend::ApplicationController
  defaults resource_class: Service, collection_name: 'services', instance_name: 'service'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Services", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ApplicationController
  defaults resource_class: User, collection_name: 'users', instance_name: 'user'
  include UserFilter

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Users", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::ApplicationController
  defaults resource_class: WebSetting, collection_name: 'web_settings', instance_name: 'web_setting'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Web Settings", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def new
    add_breadcrumb "New"
    super
  end

  def edit
    add_breadcrumb "Edit"
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/views/backend/products/_form.html.slim
.row
  .col-md-12
    .well
      center
        h5 Activated
        p = f.check_box :status
  .col-md-2
    .customize-img-web-setting
      = image_tag f.object.interior_image.url(:small)
    = f.file_field :interior_image
  .col-md-3
    h6 Category
    = f.select :category, CategoryProduct.to_a, {prompt: 'Select Category'}, {class: 'form-control', required: true} 
  .col-md-7
    h6 Title
    = f.text_field :title, class: 'form-control', required: true   
  .col-md-7
    h6 File Video
    = f.file_field :video
    - if resource.video.present?
      = link_to resource.video_file_name, download_backend_products_path(resource)
  .col-md-12
    h6 Description
    = f.cktext_area :description, class: 'form-control', required: true 
  .col-md-6
    h6 Price on the Road
    = f.number_field :price_on_the_road, class: 'form-control', required: true 
  .col-md-6
    h6 Price of the Road
    = f.number_field :price_of_the_road, class: 'form-control', required: true 
.row
  h3 Overviews
  hr
  .row
    = render partial: 'specification_form', locals: {f: f}
.row
  h3 Galleries
  hr
  .row
    = render partial: 'gallery_form', locals: {f: f}

app/views/backend/products/_gallery_fields.html.slim
.col-md-6.nested-fields
  .well
    .row
      .col-md-4
        .customize-img-web-setting
          = image_tag f.object.file.url, id: 'view_img'
        = f.file_field :file
      .col-md-8
        .row
          .col-md-12
            = link_to_remove_association "<i class='fa fa-times'></i>".html_safe, f, class: 'btn btn-danger btn-xs pull-right'
            h6 Title
            = f.text_field :title, class: 'form-control', placeholder: 'Title'
          .col-md-6
            h6 Position
            = f.number_field :position, class: 'form-control'

app/views/backend/products/_gallery_form.html.slim
= f.fields_for :galleries do |g|
  = render 'gallery_fields', f: g

.col-md-12
  = link_to_add_association f, :galleries, partial: 'gallery_fields', class: "btn btn-success btn-sm" do
    i class="fa fa-picture-o"
    span Add Image

app/views/backend/products/_specification_fields.html.slim
.col-md-6.nested-fields
  .well
    .row
      .col-md-12
        .row
          .col-md-12
            = link_to_remove_association "<i class='fa fa-times'></i>".html_safe, f, class: 'btn btn-danger btn-xs pull-right'
            h6 Description
            = f.text_area :description, class: 'form-control', placeholder: 'Description'

app/views/backend/products/_specification_form.html.slim
= f.fields_for :specifications do |s|
  = render 'specification_fields', f: s

.col-md-12
  = link_to_add_association f, :specifications, partial: 'specification_fields', class: "btn btn-success btn-sm" do
    i class="fa fa-picture-o"
    span Add Spec

app/views/backend/products/edit.html.slim
= render partial: 'backend/shareds/prepare_form',
            locals: { form_name: 'Products', action_name: 'Edit', form_method: 'put'}

app/views/backend/products/index.html.slim
= render 'backend/shareds/heading', table_name: collection.name
= render 'backend/shareds/search_form'
br
= form_for :multiple, url: "#{collection_path}/do_multiple_act", method: 'post' do
  .portlet
    = render partial: 'backend/shareds/prepare_table', locals: {table_name: 'Products', button_name: 'Products', add_method: true}  
    .portlet-content
      .widget
        .widget-content
          .table-responsive
            table class="table table-striped table-bordered table-hover"
              thead
                tr
                  th width="5%" #
                  th Picture
                  th Code
                  th Title
                  th Category
                  th Status
                  th Created At
                  th width='10%' Action
              tbody
                - @collection.each_with_index do |resource, index| 
                  tr
                    td = check_box_tag 'ids[]', resource.id
                    td
                      = image_tag "#{resource.galleries.first.file.url(:small)}", class: 'thumb-car'
                    td 
                      b = resource.code
                    td = resource.title
                    td = resource.category.titleize
                    td = resource.status?
                    td = resource.try(:created_at).strftime("%B, %d, %Y")
                    td
                      = render partial: 'backend/shareds/prepare_action',
                        locals: { resource: resource, confirmation: "Are you sure delete this #{resource.id}", no_show: false } 
          .widget-foot
            .pull-right
              = paginate @collection 
            .clearfix

app/views/backend/products/new.html.slim
= render partial: 'backend/shareds/prepare_form',
            locals: { form_name: 'Products', action_name: 'New', form_method: 'post'} 