config/routes.rb
Rails.application.routes.draw do

  # FRONTEND IN STAGING SERVER
  # scope '/prestige' do
  #   get 'about', to: 'public#about', as: 'about'
  #   get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  #   get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  #   get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  #   get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  #   get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  #   get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  #   get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  #   get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  #   get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  #   get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  #   get '/', to: "public#home", as: 'root'
  # end

  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  },
  path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register'
  }

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'

    resources :users
    resources :admins
    resources :articles do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
        get :download
      end
    end
    resources :contacts do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :services do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end

  root 'public#home'
  get 'home', to: 'public#home', as: 'home'
  get 'about', to: 'public#about', as: 'about'
  get 'product_v1', to: 'public#product_v1', as: 'product_v1'
  get 'product_v2', to: 'public#product_v2', as: 'product_v2'
  get 'product_single_v1', to: 'public#product_single_v1', as: 'product_single_v1'
  get 'product_single_v2', to: 'public#product_single_v2', as: 'product_single_v2'
  get 'contact_us', to: 'public#contact_us', as: 'contact_us'
  get 'news_event_single', to: 'public#news_event_single', as: 'news_event_single'
  get 'news_event_v2', to: 'public#news_event_v2', as: 'news_event_v2'
  get 'news_event_v1', to: 'public#news_event_v1', as: 'news_event_v1'
  get 'video_blog', to: 'public#video_blog', as: 'video_blog'
  get 'video_blog_single', to: 'public#video_blog_single', as: 'video_blog_single'
  # get '/', to: "public#home", as: 'root'

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
  add_breadcrumb "Dashboard", :backend_dashboard_path

  def dashboard
  end
end

app/views/shareds/home/_about_us.html.slim
section.dealer-about-home
  .container
    .row
      .col-md-12
        .title
          | Prestige Image Motorcars

        .description
          | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis repellat repudiandae accusantium, facilis consequuntur officia, voluptatem libero beatae voluptate ipsa id distinctio corporis at dicta, voluptatibus natus asperiores enim autem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis repellat repudiandae accusantium, facilis consequuntur officia, voluptatem libero beatae voluptate ipsa id distinctio corporis at dicta, voluptatibus natus asperiores enim autem.

      .col-md-12
        .link-load-more
          = link_to 'Read More', about_path, class: 'link-underline'

app/views/shareds/home/_list_facebook_social.html.slim
.row
  .widget-social
    = '<div class="fb-page" data-href="https://www.facebook.com/PrestigeCarsIndonesia" data-height="612" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/PrestigeCarsIndonesia"><a href="https://www.facebook.com/PrestigeCarsIndonesia">Prestige Image Motorcars</a></blockquote></div></div>'.html_safe

app/views/shareds/home/_list_news_event.html.slim
.row
  .col-md-12
    = link_to news_event_v2_path
      h2 News & Event

  .col-md-6.col-sm-6.col-xs-12
    .row
      .event-list-header
        span PRESTIGE Event

      - (1..5).each
        .event-list-body
          .col-md-3
            .row
              .image-product
                = image_tag '3.jpg', alt: 'YOUR TITLE'
          .col-md-9
            .row
              .event-description
                .title
                  = link_to news_event_single_path
                    | Independent Drive 2015

                .description
                  | This month, Prestige Motorcars is proud to present our August...


  .col-md-6.col-sm-6.col-xs-12
    .row
      .event-list-header
        span.txt-color-black Otomotive Event

      - (1..5).each
        .event-list-body
          .col-md-3
            .row
              .image-product
                = image_tag '3.jpg', alt: 'YOUR TITLE'
          .col-md-9
            .row
              .event-description
                .title
                  = link_to news_event_single_path, class: 'txt-color-black'
                    | Independent Drive 2015

                .description
                  | This month, Prestige Motorcars is proud to present our August...
.row
  .col-md-12
    .row
      .link-load-more
        = link_to 'Load More', news_event_v2_path, class: 'link-underline'

app/views/shareds/home/_news_event.html.slim
section.dealer-event-list
  .container
    .col-md-8
      = render 'shareds/home/list_news_event'

    .col-md-4
      = render 'shareds/home/list_facebook_social'

app/views/shareds/home/_recent_product.html.slim
section.dealer-slide-product
  .container
    .row
      .col-md-12
        = link_to product_v1_path
          .title
            | Recent Product

  .container
    .carousel.carousel_recent_product_3.slide.media-carousel#media
      .carousel-inner
        - (1..15).each
          .recent-product-3-item.col-md-4
            = link_to product_single_v2_path
              .image-box-recent-product
                = image_tag '1.jpg', class: 'img-responsive'

      a data-slide="prev" href="#media" class="left carousel-control"
        | ‹
      a data-slide="next" href="#media" class="right carousel-control"
        | ›

app/views/shareds/home/_slider.html.slim
.modern-slider-prestigecar.page-wrapper
  .main-slider
    .tp-banner-container
      .tp-banner
        ul
          li data-transition="slideleft" data-slotamount="1" data-masterspeed="1000" data-thumb="#{ image_url '1.jpg' }" data-saveperformance="off" data-title="We are Awesome"
            = image_tag '1.jpg', data: { bgposition: "center top", bgfit: "cover", bgrepeat: "no-repeat" }
            .tp-caption.lfb.tp-resizeme data-x="left" data-hoffset="15" data-y="center" data-voffset="-40" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01"  data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn"
              .box-information-slider
                .title
                  | Exclusivity, inspiration,
                  br
                  | and luxury is what we aim for
                .link-load-more.margin-top-50.txt-left
                  = link_to 'SEE OUR PRODUCT', product_v1_path, class: 'link-underline'

          / li data-transition="slideleft" data-slotamount="1" data-masterspeed="1000" data-thumb="#{ image_url '4.jpg' }" data-saveperformance="off" data-title="We are Awesome"
          /   iframe.embed-responsive-item height="100%" src="https://www.youtube.com/embed/TrQ9nqYFY4A" width="100%"

          li data-transition="slideup" data-slotamount="1" data-masterspeed="1000" data-thumb="#{ image_url '9.jpg' }" data-saveperformance="off" data-title="We are Awesome"
            = image_tag '9.jpg', data: { bgposition: "center top", bgfit: "cover", bgrepeat: "no-repeat" }
            .tp-caption.lfb.tp-resizeme data-x="left" data-hoffset="15" data-y="center" data-voffset="-40" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01"  data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn"
              .box-information-slider
                .title
                  | Exclusivity, inspiration,
                  br
                  | and luxury is what we aim for
                .link-load-more.margin-top-50.txt-left
                  = link_to 'SEE OUR PRODUCT', product_v1_path, class: 'link-underline'

          li data-transition="slideleft" data-slotamount="1" data-masterspeed="1000" data-thumb="#{ image_url '8.jpg' }" data-saveperformance="off" data-title="We are Awesome"
            = image_tag '8.jpg', data: { bgposition: "center top", bgfit: "cover", bgrepeat: "no-repeat" }
            .tp-caption.lfb.tp-resizeme data-x="left" data-hoffset="15" data-y="center" data-voffset="-40" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01"  data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn"
              .box-information-slider
                .title
                  | Exclusivity, inspiration,
                  br
                  | and luxury is what we aim for
                .link-load-more.margin-top-50.txt-left
                  = link_to 'SEE OUR PRODUCT', product_v1_path, class: 'link-underline'
        .tp-bannertimer

app/views/shareds/home/_two_product.html.slim
section.dealer-two-product
  .image-product
    figure
      = image_tag '7.jpg'

    .image-overlay-title
      | New Cars
    .red
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v1_path

      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v1_path
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v1_path
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v1_path

  .image-product
    figure
      = image_tag '1.jpg'

    .image-overlay-title
      | Second Hand Cars
    .red
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v2_path

      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v2_path
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v2_path
      .col-md-6.col-sm-6.col-xs-6
        .row
          .t-image-box
            = image_tag '4.jpg'
            .t-image-hover
              = link_to 'Ferarri RXV5 Sport', product_single_v2_path

app/views/shareds/home/_video_blog.html.slim
section.dealer-video-blog
  .container
    .row
      .col-md-10.col-md-offset-1
        .title
          | Video Blog

        .description
          | It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. when an unknown printer took a galley of type and scrambled it to make a type specimen book.

  .container
    .row
      ul#og-grid.og-grid
        - (1..8).each
          li
            = link_to "#", data: { videosrc: "http://www.youtube.com/embed/zpOULjyy-n8?rel=0", title: "Azuki bean", description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. when an unknown printer took a galley of type and scrambled it to make a type specimen book. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. when an unknown printer took a galley of type and scrambled it to make a type specimen book. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. when an unknown printer took a galley of type and scrambled it to make a type specimen book." }, class: 'image-google-wrapper'
              .box-image-og-grid
                = image_tag '8.jpg'
                span.overlay-image
                  span.fa.fa-play
              br
              span.text-center.txt-color-black
                | Lamborghni Racing